name: Push to GitLab

on: 
  push:
    branches:
      - master  # or the branch you want to trigger this on

jobs:
  push-to-gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "pettaaro"
          git config --global user.email "aaron.pettit@utah.edu"

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@hpcgitlab.hpcondemand.inl.gov/pettaaro/CPDSSS-proof.git
          git push -u gitlab master  # or the branch you're syncing

